/* Copyright (C) Ryan Kingstone - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 * Written by Ryan Kingstone <ryan.kingstone@outlook.com>
 */

#define TRANSPARENT 0xFFFFFF00

// standard palette
#define WHITE 	0xFFFFFFFF
#define BLACK 	0x00000000
#define GREY 	0x808080FF
#define BLUE 	0x0073FFFF
#define GREEN 	0x00E228FF
#define ORANGE 	0xFFA000FF
#define RED 	0xCC5D5DFF
#define LIME 	0x00FF96FF
#define PINK 	0xFFAFD7FF
#define PURPLE 	0xDB00AFFF
#define YELLOW 	0xF5FF00FF
#define LIBLUE 	0x00FFFFFF
#define LIRED 	0xFF6347AA
#define LIGREEN 0x00FF28FF

// admin on duty colour
#define ADUTY 	0x78AB4600

// ic chat (local)
#define SHOUT 	0xFF8000DE
#define WHISPER 0x8080FFDE
#define ACTION	0xC2A2DAAA

// radio, sms, etc
#define RADIO 	0xFFE6B3AA
#define SMS 	0xAAAF81AA

// global broadcasts (ie. adverts, government announcements)
#define ADVERT 	0x44FF44FF
#define DEPART 	0xD66F62FF

// ooc stuff
#define DONATOR 0x99660000

// label colours
#define CORPSE	0x0073FFFF
#define BIZ		0x668B8BFF
#define HOUSE	0x78AB46FF