/* Copyright (C) Ryan Kingstone - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 * Written by Ryan Kingstone <ryan.kingstone@outlook.com>
 */

/*
new Text:TDraw_ALPR_Name;

// In OnGameModeInit
TDraw_ALPR_Name = TextDrawCreate(18 ,322 , "Vehicle Type: N/A");
TextDrawFont(TDraw_ALPR_Name , 1);
TextDrawLetterSize(TDraw_ALPR_Name , 0.5, 3.5);
TextDrawColor(TDraw_ALPR_Name , 0xadadadFF);
TextDrawSetOutline(TDraw_ALPR_Name , false);
TextDrawSetProportional(TDraw_ALPR_Name , true);
TextDrawSetShadow(TDraw_ALPR_Name , 1);
*/